# Copyright (C) 2022 Shra1V32 <namanageshwar@outlook.com>
name: Tata Sky Daily Workflow
on:
 schedule:
   - cron: "00 21  * * *"
 workflow_dispatch:
  inputs:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Daily Loop
      run: |
            git config --global user.name "$git_id"
            git config --global user.email "$git_mail"
            git clone https://$git_token@github.com/$git_id/TataSkyIPTV-Daily
            cd TataSkyIPTV-Daily/
            cd code_samples/
            curl -s 'https://raw.githubusercontent.com/ForceGT/Tata-Sky-IPTV/master/code_samples/allChannels.json' > allChannels.json
            chmod 755 *
            python3 utils.py ${playlist_args}
            git clone ${gist_url}
            rm ${dir}/allChannelPlaylist.m3u
            mv *.m3u ${dir}/
            cd ${dir}
            git add .
            git commit --amend -m "Playlist has been updated."
            git push -f
